name: Trigger CodePipeline

on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  trigger-pipeline:
    runs-on: ubuntu-latest
    steps:
      - name: Configure AWS credentials via OIDC
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::333091152645:role/github-actions-trigger-pipeline
          aws-region: eu-north-1

      - name: Trigger CodePipeline
        run: |
          aws codepipeline start-pipeline-execution --name test-github-trigger
          
